### ISSUE TITLE
Erro no request

### ISSUE THREAD

**Issue by pavini** [banzeh/cielo#12]
Caro Banzeh.

Estou tentando fazer um teste simples, mas recebo sempre o mesmo erro:

`2018-07-27T21:08:18.832Z

 [Arguments] {
  '0': 'erro no request ',
  '1':
   { Error: read ECONNRESET
       at TLSWrap.onread (net.js:656:25) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' } }

------------ END DEBUG ------------

CEIELO ERRO { Error: read ECONNRESET
    at TLSWrap.onread (net.js:656:25) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }`

O código que estou usando no teste é esse:

`const paramsCielo = {
	// SANDBOX
	MerchantId: "xxxxxxxx",
	MerchantKey: "xxxxxxxxxx",

	sandbox: true, // Opcional - Ambiente de Testes
	debug: true // Opcional - Exibe os dados enviados na requisição para a Cielo
};

const cielo = require("./node_modules/cielo")(paramsCielo);

const dadosSale = {
	MerchantOrderId: "2014111703",
	Customer: {
		Name: "Comprador crédito simples"
	},
	Payment: {
		Type: "CreditCard",
		Amount: 15700,
		Installments: 1,
		SoftDescriptor: "123456789ABCD",
		CreditCard: {
			CardNumber: "0000000000000001",
			Holder: "Teste Holder",
			ExpirationDate: "12/2030",
			SecurityCode: "123",
			Brand: "Visa"
		}
	}
};

cielo.creditCard
	.completeTransaction(dadosSale)
	.then(data => {
		console.log("CEIELO SUCESSO ", data);
		//response.send(data);
	})
	.catch(err => {
		console.error("CEIELO ERRO", err);
		//response.send(err);
	});
`
Abcs

André

**Comment by banzeh** [comment]
@pavini bom dia.

Fiz as correções e já subi para o npm a versão 1.0.7. 

Atualize o pacote e deverá funcionar corretamente.

Att.
Flavio
