### ISSUE TITLE
Aplicação quebra e não exibe corretamente o erro

### ISSUE THREAD

**Issue by virgiliomax** [banzeh/cielo#18]
Estou tentando desenvolver uma API com Node JS utilizando seu client. Funciona normalmente, se tudo correr bem, ou seja se faltar um parâmetro por exemplo, a aplicação finaliza e não exibe de maneira amigável o retorno do erro  (API Cielo).  Gostaria de uma ajuda. 
Segue o erro abaixo. Observação: **node v8.9.0** e estou utilizando **async/away**.

```js
/home/max/Agendamento/1972-master/node_modules/cielo/lib/library.js:29
        if ([200, 201].indexOf(statusCode) === -1) throw new Error(`Ocorre um erro ao fazer a requisição. StatusCode: ${statusCode}`)
                                                   ^

Error: Ocorre um erro ao fazer a requisição. StatusCode: 400
    at IncomingMessage.<anonymous> (/home/max/Agendamento/1972-master/node_modules/cielo/lib/library.js:29:58)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
Segue parte do service (com CardNumber = "", propositalmente)

```js
exports.creditoSimples = async() => {
    var dadosSale = {  
        "MerchantOrderId":"CONSULTA2019000001",
        "Customer":{  
           "Name":"Comprador crédito simples"
        },
        "Payment":{  
          "Type":"CreditCard",
          "Amount":15700,
          "Installments":1,
          "SoftDescriptor":"123456789ABCD",
          "CreditCard":{  
              "CardNumber":"",
              "Holder":"Teste Holder",
              "ExpirationDate":"12/2030",
              "SecurityCode":"123",
              "Brand":"Visa"
          }
        }
     }
     const transaction = await cielo.creditCard.simpleTransaction(dadosSale);
     return transaction;
}
```
Segue parte do controller

```js
// Transação Simples
exports.post = async(req, res, next) => {
    
    try {
        var data = await svCielo.creditoSimples();
        console.log('Crédito Simples ->', data)
        res.status(201).send({
            message: 'Transação realizada com sucesso!'
        });
    } catch (e) {
        console.log(e);
        res.status(500).send({
            message: 'Falha ao processar sua requisição'
        });
    }
};
```
Rota utilizada

`router.post('/simples', controller.post);`

**Comment by banzeh** [comment]
@virgiliomax Atualiza o pacote Cielo para a versão 1.1.0 e seu código deve funcionar corretamente agora 👍 

Já havia alterado para não gerar a exceção mas ainda não havia publicado o pacote no npm. Agora está no ar.

Abraços;
