### ISSUE TITLE
Problem to initialize it.

### ISSUE THREAD

**Issue by anzileiro** [banzeh/cielo#63]
**Describe the bug**
Can't initialize the cielo instance using the keyword new.

**To Reproduce**
1. Go to install its package: https://github.com/banzeh/cielo#-installation
2. Go to initialize its instance https://github.com/banzeh/cielo#iniciando
4. See error:

`TypeError: cielo_1.Cielo is not a constructor
    at Object.<anonymous> (/Users/anzileiro/projects/azdata/history-market-cron/src/cielo.ts:13:21)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Module.m._compile (/Users/anzileiro/.nvm/versions/node/v12.14.0/lib/node_modules/ts-node/src/index.ts:814:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/anzileiro/.nvm/versions/node/v12.14.0/lib/node_modules/ts-node/src/index.ts:817:12)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at main (/Users/anzileiro/.nvm/versions/node/v12.14.0/lib/node_modules/ts-node/src/bin.ts:226:14)
    at Object.<anonymous> (/Users/anzileiro/.nvm/versions/node/v12.14.0/lib/node_modules/ts-node/src/bin.ts:485:3)`

**Expected behavior**
To get the instance.

**Screenshots**
<img width="1026" alt="Screen Shot 2020-05-18 at 14 13 11" src="https://user-images.githubusercontent.com/3415671/82240863-87334780-9911-11ea-8852-b53eb5ba85f6.png">

**Desktop (please complete the following information):**
 - OS: [MacOS Catalina 10.15.4]

**Comment by banzeh** [comment]
@anzileiro consegue postar o código aqui para eu dar uma olhada?

Testei com o código abaixo e funcionou normalmente.

```ts
import {
  Cielo,
  CieloConstructor,
  TransactionCreditCardRequestModel,
  EnumBrands,
  EnumCardType
} from 'cielo';

const cieloParams: CieloConstructor = {
    merchantId: 'dbe5e423-ed15-4c27-843a-fedf325ea67c',
    merchantKey: 'NPGKHFARFASEZEPYEYLTXJMWACSWDEMJWBAKWPQD',
    sandbox: true, // Opcional - Ambiente de Testes
}

const cielo = new Cielo(cieloParams);


const vendaParams: TransactionCreditCardRequestModel = {
  customer: {
      name: "Comprádor Teste Cíéló Áá",
  },
  merchantOrderId: "TypescriptSDK-banzeh",
  payment: {
      amount: 10000,
      creditCard: {
          brand: EnumBrands.VISA,
          cardNumber: "4532117080573700",
          holder: "Comprador T Cielo",
          expirationDate: "12/2021",
      },
      installments: 1,
      softDescriptor: "Banzeh",
      type: EnumCardType.CREDIT,
      capture: false,
  },
};
cielo.creditCard.transaction(vendaParams)
  .then((venda) => console.log('VENDA CIELO', JSON.stringify(venda, null, '\t')))
  .catch((err) => console.error(err));
```

**Comment by xGANDx** [comment]
Boa noite @banzeh , tudo certo? 

Estou com o mesmo erro que o @anzileiro, rodei exatamente o código que você mandou.

Repo exemplo: https://github.com/xGANDx/cielo_api_test

Erro rodando via docker-compose:
<img width="685" alt="Screen Shot 2020-05-26 at 18 34 39" src="https://user-images.githubusercontent.com/10067343/82952599-a409f380-9f7f-11ea-986d-eb14186b0322.png">

**Comment by anzileiro** [comment]
@banzeh malz pela demora, dias corridos!

Mas segue o código que usei no dia:

<img width="609" alt="Screen Shot 2020-05-26 at 20 13 13" src="https://user-images.githubusercontent.com/3415671/82959006-2816a800-9f8d-11ea-9a85-38bea4b5681b.png">

**Comment by anzileiro** [comment]
> @anzileiro consegue postar o código aqui para eu dar uma olhada?
> 
> Testei com o código abaixo e funcionou normalmente.
> 
> ```ts
> import {
>   Cielo,
>   CieloConstructor,
>   TransactionCreditCardRequestModel,
>   EnumBrands,
>   EnumCardType
> } from 'cielo';
> 
> const cieloParams: CieloConstructor = {
>     merchantId: 'dbe5e423-ed15-4c27-843a-fedf325ea67c',
>     merchantKey: 'NPGKHFARFASEZEPYEYLTXJMWACSWDEMJWBAKWPQD',
>     sandbox: true, // Opcional - Ambiente de Testes
> }
> 
> const cielo = new Cielo(cieloParams);
> 
> 
> const vendaParams: TransactionCreditCardRequestModel = {
>   customer: {
>       name: "Comprádor Teste Cíéló Áá",
>   },
>   merchantOrderId: "TypescriptSDK-banzeh",
>   payment: {
>       amount: 10000,
>       creditCard: {
>           brand: EnumBrands.VISA,
>           cardNumber: "4532117080573700",
>           holder: "Comprador T Cielo",
>           expirationDate: "12/2021",
>       },
>       installments: 1,
>       softDescriptor: "Banzeh",
>       type: EnumCardType.CREDIT,
>       capture: false,
>   },
> };
> cielo.creditCard.transaction(vendaParams)
>   .then((venda) => console.log('VENDA CIELO', JSON.stringify(venda, null, '\t')))
>   .catch((err) => console.error(err));
> ```

Throws:

/Users/anzileiro/projects/azdata/history-market-cron/src/cielo.ts:36
const cielo = new Cielo(cieloParams);
              ^
TypeError: cielo_1.Cielo is not a constructor
    at Object.<anonymous> (/Users/anzileiro/projects/azdata/history-market-cron/src/cielo.ts:36:15)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Module.m._compile (/Users/anzileiro/.nvm/versions/node/v12.16.3/lib/node_modules/ts-node/src/index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/anzileiro/.nvm/versions/node/v12.16.3/lib/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at main (/Users/anzileiro/.nvm/versions/node/v12.16.3/lib/node_modules/ts-node/src/bin.ts:227:14)
    at Object.<anonymous> (/Users/anzileiro/.nvm/versions/node/v12.16.3/lib/node_modules/ts-node/src/bin.ts:513:3)

**Comment by banzeh** [comment]
@anzileiro e @xGANDx, acabei de subir o pacote na versão 2.2.6.

Essa versão corrige esse erro.

Qualquer dúvida é só chamarem aqui.

Abraços.
